//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Comprador = new HashSet<Comprador>();
            this.Usuarios = new HashSet<Usuarios>();
            this.Vendedor = new HashSet<Vendedor>();
            this.Usuarios1 = new HashSet<Usuarios>();
        }
    
        public string Descripcion { get; set; }
        public int IDrol { get; set; }
    
        public virtual ICollection<Comprador> Comprador { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual ICollection<Vendedor> Vendedor { get; set; }
        public virtual ICollection<Usuarios> Usuarios1 { get; set; }
    }
}
