//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Roles1 = new HashSet<Roles>();
        }
    
        public int DocNumero { get; set; }
        public int IDusuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int RolActual { get; set; }
    
        public virtual Comprador Comprador { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        public virtual ICollection<Roles> Roles1 { get; set; }
    }
}
