//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public Vendedor()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public int IDusuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ContrasenaUsuario { get; set; }
        public Nullable<int> IDrol { get; set; }
    
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
