//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaArticulo
    {
        public int IDarticulo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IDcomprador { get; set; }
        public decimal PrecioSalida { get; set; }
        public decimal PrecioVenta { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Comprador Comprador { get; set; }
    }
}
